In [1]:
from transformers import LlamaForCausalLM, LlamaTokenizer, AutoTokenizer, AutoModelForCausalLM
import os
import numpy as np
import torch

In [2]:
base_model = "meta-llama/Llama-2-7b-chat-hf"
# llama_model = "meta-llama/Meta-Llama-3-8B-Instruct"

device_map = 'auto'
max_memory_mapping = {0: "23GiB", 1: "23GiB"}

In [3]:
tokenizer = LlamaTokenizer.from_pretrained(base_model,
                                           padding_side = "left",
                                           add_eos_token = True,
                                           add_bos_token = True,                                        
                                           token = os.environ.get("HUGGINGFACE_ACCESS_TOKEN"),
)
tokenizer.add_special_tokens({"pad_token":"<pad>"})

1

In [4]:
print(f"pad_token_id={tokenizer.pad_token_id}")

pad_token_id=32000


In [5]:
model = LlamaForCausalLM.from_pretrained(
        base_model,
        load_in_8bit=True,
        torch_dtype=torch.float16,
        device_map=device_map,
        max_memory = max_memory_mapping,
        token = os.environ.get("HUGGINGFACE_ACCESS_TOKEN"),
    ).eval()
model.resize_token_embeddings(len(tokenizer),pad_to_multiple_of=8)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Embedding(32008, 4096)

In [6]:
tokenizer.vocab_size

32000

In [7]:
import json
train_data_path = './final_data/movie/train.json'
with open(train_data_path, 'r') as f:
    train_data = json.load(f)
print(len(train_data))

3200


In [8]:
def create_data(d):
    return d["instruction"] + "\n" + d["input"]

In [9]:
prompt = [
    create_data(train_data[0]),
    create_data(train_data[1])
]
print(prompt)
inputs = tokenizer(prompt, return_tensors="pt", padding = True)
print(inputs)

['You are an expert movie critic and recommender. Given the user profile and list of recent liked and disliked movies, identify whether the user will like the target movie or not by providing reasoning for the same. Please follow further instruction below.\nUser Profile - \n            The user has a diverse taste in movies, with a preference for thought-provoking and emotionally engaging films. They enjoy dramas that explore complex themes such as mental illness, racial injustice, and the meaning of life. The user is drawn to movies that challenge their perspective and provoke deep thought, often favoring those that tackle serious and mature subjects.\n            \n            In addition to dramas, the user also has a soft spot for classic Disney films, as evidenced by their fondness for Cinderella. They appreciate the enchanting storytelling and timeless charm of these animated tales.\n            \n            The user\'s taste in movies also extends to comedies, as seen in their 

In [10]:
generate_ids = model.generate(inputs.input_ids, max_length=64)
print(generate_ids)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.
/home/grads/m/mbismay/miniconda3/envs/mixtral/lib/python3.9/site-packages/transformers/generation/utils.py:1141: UserWarning: Input length of input_ids is 1424, but `max_length` is set to 64. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.
  warnings.warn(
/home/grads/m/mbismay/miniconda3/envs/mixtral/lib/python3.9/site-packages/transformers/generation/utils.py:1413: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids =

tensor([[  2675,    527,    459,  ...,    198,    257,   1038],
        [128256, 128256, 128256,  ...,    198,    257,    220]])


In [11]:
tokenizer.batch_decode(generate_ids, skip_special_tokens=False, clean_up_tokenization_spaces=True)

['You are an expert movie critic and recommender. Given the user profile and list of recent liked and disliked movies, identify whether the user will like the target movie or not by providing reasoning for the same. Please follow further instruction below.\nUser Profile - \n            The user has a diverse taste in movies, with a preference for thought-provoking and emotionally engaging films. They enjoy dramas that explore complex themes such as mental illness, racial injustice, and the meaning of life. The user is drawn to movies that challenge their perspective and provoke deep thought, often favoring those that tackle serious and mature subjects.\n            \n            In addition to dramas, the user also has a soft spot for classic Disney films, as evidenced by their fondness for Cinderella. They appreciate the enchanting storytelling and timeless charm of these animated tales.\n            \n            The user\'s taste in movies also extends to comedies, as seen in their 

In [13]:
messages = [
    {"role": "system", "content": train_data[0]['instruction']},
    {"role": "user", "content": train_data[0]['input']},
]

In [14]:
input_ids = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_tensors="pt"
).to(model.device)
print(input_ids)

tensor([[128000, 128006,   9125,  ...,  78191, 128007,    271]],
       device='cuda:2')


In [18]:
tokenizer.decode(input_ids[0])

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nYou are an expert movie critic and recommender. Given the user profile and list of recent liked and disliked movies, identify whether the user will like the target movie or not by providing reasoning for the same. Please follow further instruction below.<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nUser Profile - \n            The user has a diverse taste in movies, with a preference for thought-provoking and emotionally engaging films. They enjoy dramas that explore complex themes such as mental illness, racial injustice, and the meaning of life. The user is drawn to movies that challenge their perspective and provoke deep thought, often favoring those that tackle serious and mature subjects.\n            \n            In addition to dramas, the user also has a soft spot for classic Disney films, as evidenced by their fondness for Cinderella. They appreciate the enchanting storytelling and timeless charm of these 

In [15]:
terminators = [
    tokenizer.eos_token_id,
    tokenizer.convert_tokens_to_ids("<|eot_id|>")
]
outputs = model.generate(
    input_ids,
    max_new_tokens=256,
    eos_token_id=terminators,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:128001 for open-end generation.


In [16]:
response = outputs[0][input_ids.shape[-1]:]
print(tokenizer.decode(response, skip_special_tokens=True))

Summary of user behavior:
The user has a diverse taste in movies, preferring thought-provoking dramas, classic Disney films, comedies, and adventure films. They enjoy stories with complex themes, enchanting storytelling, and memorable characters. The user tends to avoid horror movies and overly violent or graphic content.

Movie characteristics liked by the user:
* Whimsical and visually stunning adaptations
* Heartwarming and emotionally engaging stories
* Enchanting animation and memorable characters
* Themes of friendship, healing, and individuality
* Classic Disney films with timeless charm
* Comedies with clever wordplay and slapstick humor
* Adventure films with memorable characters and thrilling storylines

Movie characteristics disliked by the user:
* Horror movies
* Overly violent or graphic content

Prediction: Yes

Reasoning: Mulan is a captivating animated film that tells the empowering story of a young Chinese woman who disguises herself as a man to fight in the army. The 

In [12]:
tokenizer.eos_token

'<|end_of_text|>'

In [41]:
prompt = [': Yes']
inputs = tokenizer(prompt, return_tensors="pt", padding = True)
print(inputs)

{'input_ids': tensor([[   1,  584, 3869,    2]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


In [1]:
tokenizer.batch_decode([29901, 3869], skip_special_tokens=True, clean_up_tokenization_spaces=False)

NameError: name 'tokenizer' is not defined

In [44]:
l = [[1,2,1,3,1,3,4,45,1,3], [1,2,1,3,1,3,4,45,1,3]]
l1 = [[n if n!=1 else 0 for n in label] for label in l]
l1, l

([[0, 2, 0, 3, 0, 3, 4, 45, 0, 3], [0, 2, 0, 3, 0, 3, 4, 45, 0, 3]],
 [[1, 2, 1, 3, 1, 3, 4, 45, 1, 3], [1, 2, 1, 3, 1, 3, 4, 45, 1, 3]])

In [7]:
from transformers import AutoTokenizer, LlamaForCausalLM

prompt = "Hey, are you conscious? Can you talk to me?"
inputs = tokenizer(prompt, return_tensors="pt")

# Generate
generate_ids = model.generate(inputs.input_ids, max_length=30)
tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]

/home/grads/m/mbismay/miniconda3/envs/mixtral/lib/python3.9/site-packages/transformers/generation/utils.py:1413: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(


'Hey, are you conscious? Can you talk to me?\nЉ�д�д�д�д�д�д�д'

### Mistral 7B Instruct v0.2

In [5]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import os
import torch
# device = "cuda" # the device to load the model onto
device_map = 'auto'
max_memory_mapping = {0: "23GiB", 1: "23GiB"}
model_id = "mistralai/Mistral-7B-Instruct-v0.2"

model = AutoModelForCausalLM.from_pretrained(model_id,
                                             token = os.environ.get("HUGGINGFACE_ACCESS_TOKEN"))
tokenizer = AutoTokenizer.from_pretrained(model_id,
                                        load_in_8bit=True,
                                        torch_dtype=torch.float16,
                                        device_map=device_map,
                                        max_memory = max_memory_mapping,
                                        token = os.environ.get("HUGGINGFACE_ACCESS_TOKEN"),)

messages = [
    {"role": "user", "content": create_data(train_data[0])}
]

encodeds = tokenizer.apply_chat_template(messages, return_tensors="pt")

model_inputs = encodeds

generated_ids = model.generate(model_inputs, max_new_tokens=1000, do_sample=True)
decoded = tokenizer.batch_decode(generated_ids)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.


<s> [INST] You are an expert movie critic and recommender. Given the user profile and list of recent liked and disliked movies, identify whether the user will like the target movie or not by providing reasoning for the same. Please follow further instruction below.
User Profile - 
            The user has a diverse taste in movies, with a preference for thought-provoking and emotionally engaging films. They enjoy dramas that explore complex themes such as mental illness, racial injustice, and the meaning of life. The user is drawn to movies that challenge their perspective and provoke deep thought, often favoring those that tackle serious and mature subjects.
            
            In addition to dramas, the user also has a soft spot for classic Disney films, as evidenced by their fondness for Cinderella. They appreciate the enchanting storytelling and timeless charm of these animated tales.
            
            The user's taste in movies also extends to comedies, as seen in thei

In [6]:
print(decoded[0].split("[/INST]")[1])


 Based on the user profile and movie watching history, the user has a diverse taste in movies, with a preference for thought-provoking and emotionally engaging films. They enjoy dramas that explore complex themes and appreciate enchanting storytelling in animated films, particularly those with a deep message or exploration of identity. The user tends to avoid horror movies, violence, and graphic content.

The user's recent movie preferences demonstrate a liking for animated films with strong narratives and complex themes, such as "Snow White and the Seven Dwarfs," "Beauty and the Beast," and "The Hunchback of Notre Dame." They also enjoy comedies, as shown by their appreciation for "Airplane!" and "Wallace & Gromit."

Given the user's history and the user profile, it is likely that they will enjoy "Mulan" due to its strong narrative, themes of empowerment, and its visual storytelling in an animated format. Additionally, the user's appreciation for deeper storytelling in animated films,

In [1]:
import operator
import time
import gc
gc.collect()

start = time.time()
def rindex(lst, value):
    return len(lst) - operator.indexOf(reversed(lst), value) - 1
lst = [3]*10000000000
lst.extend([2,5,7,3,8,9])
val = 3
print(time.time()-start, rindex(lst, val))

16.17045783996582 10000000003


In [ ]:
def find_r_index(lst, val):
    n = len(lst)
    

In [11]:
from math import log

start = time.time()
x = log(10000000000)
print(time.time() - start, x)

8.225440979003906e-05 23.025850929940457


In [ ]:
100 - 0.00024
1000 - 0.00011
100000 - 0.0043
1000000 - 0.0033
100000000 - 0.181
10000000000 - 16.06

### Testing Similarity

In [1]:
from sklearn.metrics.pairwise import cosine_similarity

In [9]:
l1 = [[1,1,1,1,1,1,1,1,1,1,1,1,1,2,3,4,7385,6221]]
l2 = [[1,1,1,1,1,1,1,1,1,1,1,1,22,1123,3,10,9,12]]
cosine_similarity(l1, l2)

array([[0.01322412]])